name: craftengine-hosts
version: '0.0.2'
main: cn.gtemc.craftengine.CraftengineHosts
api-version: '1.20'
author: 'jhqwqmc'
website: https://github.com/jhqwqmc
folia-supported: true
depend:
  - CraftEngine
